### ISSUE TITLE
Run on Linux with an error.

### ISSUE THREAD

**Issue by JamesChungZLL** [bitbar/testdroid-samples#131]
I run Image Recognition Sample in Linux, has an error:"libopencv_java2413.so: libavcodec.so.53: cannot open shared object file: No such file or directory. "

**Comment by LasseHall** [comment]
The file is located at https://github.com/bitbar/testdroid-samples/tree/master/image-recognition/lib/linux/opencv and it is defined in the code here: https://github.com/bitbar/testdroid-samples/blob/master/image-recognition/src/main/java/AkazeImageFinder.java#L367

Could you check the contents of your java.library.path with `System.getProperty("java.library.path");` during your test process?

**Comment by JamesChungZLL** [comment]
The file 'libopencv_java2413.so' has already been set to the 'java.library.path', from the message, it looks like lost the 'libavcodec.so.53', BTW, my os is ubuntu, I have test with 14.X and 16.X, and both fail with same error.

**Comment by LasseHall** [comment]
Our latest version of the image-recognition project uses now a maven-central hosted version of the OpenCV bindings, so this issue of missing libraries shouldn't anymore occur.

Please let us know, if the issue persists!
