### ISSUE TITLE
Cannot run akaze_match on aws device farm

### ISSUE THREAD

**Issue by ColtonPhillips** [bitbar/testdroid-samples#156]
I tried running akaze_match through appium on aws device farm and i got the following error:

`lib/linux/akaze/akaze_match: error while loading shared libraries: libopencv_calib3d.so.2.4: cannot open shared object file: No such file or directory`

Do you know what is causing it?

**Comment by mkaasila** [comment]
Yes, we know what is the issue. It works on Bitbar Cloud, not on AWS Device Farm.

**Comment by ColtonPhillips** [comment]
OK. Was able to recompile the code on another branch of akaze -- works. Thanks!
