### ISSUE TITLE
Server build has failed

### ISSUE THREAD

**Issue by AnandSrikumar** [bitbar/testdroid-samples#162]
The tests are failing everytime because of this!
I uploaded zip file, i uploaded apk, i checked .sh file too!
![screenshot 3](https://user-images.githubusercontent.com/37832523/39748859-de6b22ce-52ce-11e8-8baa-80adbbb523b7.png)
[devicelog.log](https://github.com/bitbar/testdroid-samples/files/1983191/devicelog.log)

**Comment by makakk** [comment]
Please make sure you zip your files without any parent folder. run-tests.sh should be at the root level of the package.
